### ISSUE TITLE
Hello, is there a way to output the unity screen to the video card of Aja?

### ISSUE THREAD

**Issue by goo110** [RenderHeads/UnityPlugin-AVProDeckLink#1]
Hello, is there a way to output the unity screen to the video card of Aja?

**Comment by AndrewRH** [comment]
This plugin is only for Blackmagic hardware I'm afraid.  It does support Output though, so you can use it for sending your Unity scene to a broadcast signal.

We would love to create a AJA specifc plugin for Unity, but we just don't have the time right now.

I hope this information helps you. Let me know if you have any more questions.
