### ISSUE TITLE
24 hours of runtime results in black display

### ISSUE THREAD

**Issue by Panic77** [RenderHeads/UnityPlugin-AVProDeckLink#10]
We are currently working on a project which controls an LED screen which takes multiple inputs. We want to target different output ports on the DeckLink 4k Extreme 12G card. Is this possible or do we need other hardware? 

How would we setup the Plugin to target different output ports?

**Comment by AndrewRH** [comment]
Yes this should certainly be possible.  
You would need to configure the DeckLinkOutput component for having multiple outputs.  You can set the device profile here:
![image](https://user-images.githubusercontent.com/5418126/73647797-2e96b200-4674-11ea-8dd1-78bf550eb1ff.png)

You can then have mutliple DeckLinkOutput components, each assigned to a different output index.
![image](https://user-images.githubusercontent.com/5418126/73647890-5be36000-4674-11ea-8ac9-c56d8e76cee2.png)

I hope this helps?  Or perhaps you found the solution yourself by now?

**Comment by Panic77** [comment]
Hi Andrew,

Thanks for getting back to me regarding the multiple outputs.

I have another question regarding video input. I have created a unity app that takes a 1080p video input, which is displayed on one of our 4k monitors in sky studios.
We have seen that after around 24 hours the input texture (uGUIDisplay) seems to go black. I can fix this by simply reselecting the input resolution within the explorer which forces the texture to reinitialise.
Is this a known issue? Or is there something I can do to prevent this from happening?

Regards,

Pani

**Comment by AndrewRH** [comment]
Hmmm....that's strange.  We haven't seen that before...
We will try to replicate it here and get back to you.
My hunch is that it must be some sort of frame counter that's overflowing internally...

**Comment by AndrewRH** [comment]
We haven't been able to reproduce this issue.

Is it still happening for you?

Otherwise we'll close this issue.

Thanks,

**Comment by Panic77** [comment]
Production have not reported this issue happening again. Happy to close this.
