### ISSUE TITLE
unity editor re-focus error

### ISSUE THREAD

**Issue by jejeblue** [RenderHeads/UnityPlugin-AVProDeckLink#11]
In unity editor, if I re-focus your sample , streamming video does not work.

**Comment by AndrewRH** [comment]
Could you give more details for steps to reproduce this please?  I don't quite understand...

**Comment by AndrewRH** [comment]
I need to investigate whether there is an issue with focus / minimising or lost D3D context

**Comment by AndrewRH** [comment]
I believe this is fixed in the latest version so I'm closing this issue.  It was related to some of the shader uniforms not being defined in the Properties section, which causes their properties to be lost when a shader reloads.
