### ISSUE TITLE
Vertical noises during output PAL 8bit 

### ISSUE THREAD

**Issue by narengenet** [RenderHeads/UnityPlugin-AVProDeckLink#12]
I'm using Black Magic Dou 2 using avpro decklink in Unity. Everything is ok with HD output until I use PAL 8bit. I need exactly this PAL 8bit for broadcast system of my TV channel which is SD not HD.
Output has vertical invisible lines which makes output noisy and details of the scene become unclear. Have you any suggest for me?

**Comment by AndrewRH** [comment]
Is it possible to share a screenshot of this vertical line artifacts?

Could it be related to interlacing?

**Comment by AndrewRH** [comment]
This will be fixed in the upcoming 1.8.4 version - closing this issue now
