### ISSUE TITLE
android played once and next time black screen no audio

### ISSUE THREAD

**Issue by pacmanamr1985** [RenderHeads/UnityPlugin-AVProDeckLink#18]
Problem description:

the movies played once and can not be played again.. shows black screen and no audio..

Device (which devices are you having the issue with - model, OS version number):

honor 7c

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

res 700x394
format wmv
frame rate 30

System Information:

AVPro Video: plugin v1.9.17 scripts v1.10.0
Target Platform: Android
Unity: v2019.2.18f1 WindowsEditor
OS: Desktop - To be filled by O.E.M. (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz - 4 threads - 4061KB
GPU: NVIDIA GeForce GTS 450 - NVIDIA - Direct3D 11.0 [level 11.0] - 969KB - 16384

**Comment by AndrewRH** [comment]
Hi,
You've posted to the wrong place...this is for the unity plugin AVPro DeckLink
you should repost your issue here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues

Thanks,
