### ISSUE TITLE
Support of QuadSDI input signal of4K-3D-60p? 

### ISSUE THREAD

**Issue by EdieBauchmann** [RenderHeads/UnityPlugin-AVProDeckLink#19]
Hello the Renderheads team, 

May I please ask for an issue about the purchased ‘AVProDeckLink’? 

We are trying to use a DeckLink 8K Pro card to get 4K-3D-60/60p video signal. 
The signal input is in the quadSDI 3840x2160 50/60p (4xBNC) format, each BNC cable delivers a fullHD 50/60p video signal. Two for the left view and two for the right.  

Could the current version of AVProDeckLink handle this with the DeckLink 8K Pro? 
It will involve fusion of four FullHD video signals into two textures for each camera. 

Thank you very much.
It would be of great help and very appreciated, if you could be so nice to reply.

**Comment by AndrewRH** [comment]
Yes, the DeckLink 8K Pro can handle stereo 4K at 60....and do can our plugin.

Is there anything else?

Thanks,
