### ISSUE TITLE
Add DirectX12 Support

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/UnityPlugin-AVProDeckLink#20]
Add support to the Windows plugin for the DirectX 12 API.

**Comment by kamilsztuke** [comment]
Any news ?

**Comment by AndrewRH** [comment]
It's in the pipeline.   We have added DirectX12 support to 2 of our other plugins (AVPro Video and Movie Capture) and DeckLink is next.

Thanks,

**Comment by Ludwig-Karl** [comment]
How does it look like? Is there a fixed date for the update? 

Thanks in advance

**Comment by RenderHeadsMrT** [comment]
Hi @Ludwig-Karl,

As per Andrew's comment DeckLink is still next for DX12 support and should be starting within a week or two. We have to balance new features with support requests so unfortunately can't give an exact date but it will be in the region of weeks rather than months.

Cheers,

**Comment by kamilsztuke** [comment]
Does AVPro DeckLink version 1.9.0 support DX12 ?

**Comment by kahnivore** [comment]
Hi @kamilsztuke 

Not yet but it is being worked on currently. Will hopefully be released sometime in September.
