### ISSUE TITLE
SDI audio input problem

### ISSUE THREAD

**Issue by gy751** [RenderHeads/UnityPlugin-AVProDeckLink#26]
I wanted to analyze the audio input from SDI, but the audio input from the InputAudioSource could not get the audio data.
How do I analyze the audio input from SDI?

**Comment by AndrewRH** [comment]
Current audio that is grabbed from the DeckLink card is played in Unity directly to an AudioSource.

You could grab this again in a few ways:
1) Change DeckLinkInput.cs there is a method OnAudioFilterRead() which is where the audio data is read in
2) Add your own Monobehaviour script to same GameObject as the DeckLinkInput component and implement OnAudioFilterRead(), or you could also add it after the AudioListener in the scene.

We realise these aren't the best solutions so we are working on offering better ways to expose these without hooking into Unity's audio pipeline.

I guess another option would be to call the native plugin directly (just as DeckLinkInput::OnAudioFilterRead() is doing).  You would have to disable that existing call though as it consumed the audio data.

I hope this helps?
