### ISSUE TITLE
Problem with Post Processing - Lose the input video from blackmagic card

### ISSUE THREAD

**Issue by battonm39** [RenderHeads/UnityPlugin-AVProDeckLink#31]
Hi,

Working with AVPro Decklink plugin and everything was working perfectly. But when I start to use post processing (FXAA) to the project and build my project. I suddenly lose my two input video feeds from the Blackmagic card. Any ideas and what step I am missing or does the plugin not like to use post processing? Thanks 

UNITY V2019.3.14f1

Marcus

**Comment by AndrewRH** [comment]
Hi Marcus,

Thanks for reporting this.

Could you tell me which version of AVPro DeckLink you're using and also which version of the post-processing?

Are you using either HDRP or URP?

What exactly do you mean by 'lose my two input video feeds'?  Is the hardware no longer detected or is just a black frame returned?

Thanks,

**Comment by battonm39** [comment]
I am currently using Post Processing V2.3.0 also the version of AvPro is 1.8.6. I am not using HDRP or URP just the built in. 

Yes sorry, the two feeds just display black instead of the two camera feeds coming in through the blackmagic card. I shut off post processing and built the project again and the video feeds returned. 

Marcus

**Comment by AndrewRH** [comment]
Hi,

I tested the plugin with Post Processing 2.3.0 with Unity 2019.4.13 (slightly newer than your version), and it worked fine.  I used a couple of our demo scenes, and added a Layer and Volume post processing component to them and a bloom filter.  Everything worked fine in the test.

Could you explain exactly how your scene is set up?  Perhaps include a screenshot or tell us how to reproduce it from one of our demo scenes.

Thanks,

**Comment by battonm39** [comment]
So I have taken screen shots of my basic setup. I have two planes in a framed box. I have attached each plane with the Decklink input script. The camera has Cinemachine installed and running a dolly back and forth.

Thank you  

![TWO_PLANES_WITH_INPUTS](https://user-images.githubusercontent.com/6867739/97885072-8722da80-1cec-11eb-9da9-50d62bd7f32d.jpg)
![DECKLINK_SETTINGS](https://user-images.githubusercontent.com/6867739/97885087-8be78e80-1cec-11eb-8421-ccdc494432b3.jpg)
![INPUT_1_SETTINGS](https://user-images.githubusercontent.com/6867739/97885092-8e49e880-1cec-11eb-9ef2-f4575f33c80c.jpg)
![INPUT_2_SETTINGS](https://user-images.githubusercontent.com/6867739/97885097-8f7b1580-1cec-11eb-8612-b723353a973c.jpg)
![MAIN_CAMERA](https://user-images.githubusercontent.com/6867739/97885105-9144d900-1cec-11eb-90f3-d262f4fda668.jpg)
![MAIN_CAMERA2](https://user-images.githubusercontent.com/6867739/97885112-930e9c80-1cec-11eb-812e-27d8486fb491.jpg)

**Comment by Chris-RH** [comment]
CNR
