### ISSUE TITLE
Class reference link access denied

### ISSUE THREAD

**Issue by genereddick** [RenderHeads/UnityPlugin-AVProDeckLink#32]
Attempting to get to the AVProDeckLinkClassReference from the link in the PDF leads to an Access Denied error page:

https://rh-downloads.s3-eu-west-1.amazonaws.com/docs/AVProDeckLinkClassReference/

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6EC2A56C2893EB95</RequestId>
<HostId>jTtI4ku2h9sXji4CxzSjb48uGbCCgKRB7MQnv1i2H9xiScvev+1XgUi8Mu5WC3GzdkFCUDWHfX4=</HostId>
</Error>
```

**Comment by AndrewRH** [comment]
Thanks for reporting this!
The correct link is:
https://www.renderheads.com/content/docs/AVProDeckLinkClassReference/

We will update the documentation.

Thanks,
