### ISSUE TITLE
Flipping X, Y influences multiple inputs when the sources come from the same hardware

### ISSUE THREAD

**Issue by D10scur0** [RenderHeads/UnityPlugin-AVProDeckLink#34]
**Describe the bug**

Flipping X or Y when using the plugin with a multiple input card will influences different inputs. See attached video for a clear overview of the issue.

Apparently the issue is present when the sources come from the same hardware, but still on different Inputs/Outputs. 

To be more explanatory in the setup: As a source we connected 2 input (0 and 1 on the Decklink card) from 2 different outputs from the graphic card of a computer, and the other 2 (2 and 3) from another.

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.15f1- HDRP
 - AVPro DeckLink version: 1.8.6t
 - Operating system version: Win 10
 - Hardware model: DeckLink Quad HDMI Recorder
 - Desktop Video version: 11.7
 - Video mode (resolution, frame-rate, pixel-format): 

**To Reproduce**
1. Create a new empty project in unity;
2. Import AvPro Decklink Trial Package;
3. Open 04_InputExplorerDemo scene;
4. Connect 2 Outputs from a Graphic card of one computer to 2 Inputs in a BlackMagic Acquisition card;
5. Play and try to flip one of the inputs;
6. Observe the issue as both the inputs get flipped;

**Videos**

https://user-images.githubusercontent.com/59603519/103538299-3f5c3300-4e96-11eb-8b55-7247a0b97407.mp4

**Comment by AndrewRH** [comment]
Thanks for reporting this - we are investigating.

**Comment by D10scur0** [comment]
Hi Andrew,

if it can be of any help, I'm raw guessing, the culprit could be in the conversion material (See picture) shared by the inputs.

![ConversionMat](https://user-images.githubusercontent.com/59603519/103907655-d973e380-5101-11eb-9d84-f9fe832195bd.png)

Disregard this comment if totally off track.

**Comment by AndrewRH** [comment]
You are correct!  We will address fix (and sorry it's taken so long)

**Comment by RichRH** [comment]
Closing as fixed in https://github.com/RenderHeads/UnityPlugin-AVProDeckLink/releases/tag/1.9.4.

Cheers,
