### ISSUE TITLE
Add timecode to output SDI

### ISSUE THREAD

**Issue by tetsutaroh** [RenderHeads/UnityPlugin-AVProDeckLink#38]
Is it possible to add timecode to the output?
I wish I could add the SDI input timecode to the output timecode.
In a similar discussion in the past, it was said that it would be supported in the future.
I would like to know if it is currently in progress.

**Comment by AndrewRH** [comment]
We're looking into this now and will hopefully have more information by the end of the week

**Comment by RenderHeadsMrT** [comment]
Duplicate of #3
