### ISSUE TITLE
Output fails with: Unable to start device Intensity Pro 4K, it might be currently busy

### ISSUE THREAD

**Issue by genereddick** [RenderHeads/UnityPlugin-AVProDeckLink#46]
**Describe the bug**

In the latest version 1.9.0 I am unable to get an Output feed from a card when Input is running. The previous version of the software with all other settings the same handles this fine.

The issue appears in this code from the current version:

From Decklink.cs

```
public void Begin(bool search = false) 
{
    ...
    if (_device != null)
    {
	bool valid = IsInput() ? _device.CanInput() : _device.CanOutput();
       if (valid) { .. .}
       else {
	     Debug.LogWarning("[AVProDeckLink] Unable to start device " + _device.Name + ", it might be currently busy");
	   _device = null;
        }
...
}
```

Here `_device.CanOutput()` calls into Device.cs

```
public bool CanOutput()
{
    bool result = SupportsOutput && !IsOutputBusy && !IsInputBusy;
    /*if (result)
    {
        if (_fullDuplexSupported)
        {
            result = !IsStreamingOutput;
        }
        else
        {
            result = !IsStreaming;
        }
    }*/
    return result;
}
```

Here  `IsInputBusy()` is returning true (thus !true) causing the Output to fail. If I hack the method to return true no matter what it works and I have both Input and Ouput working on the same device/card as in the previous version. 

For reference here is the previous version of this code (pre 1.9.0) which works.

```
public bool CanInput()
{
    if (_fullDuplexSupported)
    {
        return !IsStreamingInput;
    }
    else
    {
        return !IsStreaming;
    }
}
```

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.14f1
 - AVPro DeckLink version: 1.9.0
 - Operating system version: Windows 10
 - Hardware model: Intensity Pro 4K or Ultrastudio
 - Cables used: HDMI
 - Desktop Video version: 11.7
 - Video mode (resolution, frame-rate, pixel-format): 1080p, 24fps
 - 

**To Reproduce**
Download latest version, attempt to run InputOutputDemo scene, using Decklink Intensity Pro 4K or Ultrastudio. Check that Input and Output both work.

**Logs**
[AVProDeckLink] Unable to start device Intensity Pro 4K, it might be currently busy
UnityEngine.Debug:LogWarning (object)
RenderHeads.Media.AVProDeckLink.DeckLink:Begin (bool) (at Assets/AVProDeckLink/Scripts/Internal/DeckLink.cs:565)
RenderHeads.Media.AVProDeckLink.Demos.InputModifyOutputDemo:StartOutput (RenderHeads.Media.AVProDeckLink.DeviceMode) (at Assets/AVProDeckLink/Demos/Scripts/InputModifyOutputDemo.cs:151)
RenderHeads.Media.AVProDeckLink.Demos.InputModifyOutputDemo:OnGUI () (at Assets/AVProDeckLink/Demos/Scripts/InputModifyOutputDemo.cs:364)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by RenderHeadsMrT** [comment]
Hi @genereddick - just wanted to check if the above fix worked for you?

Cheers,
Richard

**Comment by genereddick** [comment]
Yes, the fix worked. Thanks!
