### ISSUE TITLE
Multiple input video and audio issue

### ISSUE THREAD

**Issue by UrbanSam** [RenderHeads/UnityPlugin-AVProDeckLink#47]
When using multiple decklink input, the first input feed will work properly on start, but when second one is being turn on via script .Begin(). The input feed for first one will have a green bar on top.

When I try to to turn off the first and turn it back on the feed will work properly again, but without audio.

 - Unity version: 2021.1.7f1
 - AVPro DeckLink version: 1.9.0
 - Operating system version: Windows 10
 - Hardware model: Decklink duo 2
 - Cables used: BNC Male to BNC Male RG179 75 Ohm SDI Cable
 - Desktop Video version: 12.1
 - Video mode (resolution, frame-rate, pixel-format): 1920x1080@60p 8 bit 4:2:2 YUV

Screenshot of issue here:
https://drive.google.com/file/d/1WMsRe-aPL_eOYAJdthz1ppht7LWbF-FI/view?usp=sharing

**Comment by AndrewRH** [comment]
Hi,

Thanks for reporting this issue.  Could you take a look at the solution proposed in #46 and see if that solves it for you?

Thanks,

**Comment by UrbanSam** [comment]
Hi,
I have tried implementing the fix, same issue. I just try on a empty project with the InputDemo scene, duplicate the Decklink object with DecklinkInput.cs, so I got 2 input. 

But seem to be working now, once I make sure the 2nd input is getting signal. Then it will not show anymore for some reason...
Previously it haven't had any signal thru the 2nd decklink port.

**Comment by AndrewRH** [comment]
So this seems to have been resolved, but there is an audio issue remaining...Seems like a logic bug.

**Comment by RichRH** [comment]
Closing and merging this ticket into #55.

Cheers,

**Comment by Chris-RH** [comment]
This issue has been fixed in the latest release (AVPro Decklink version 1.9.7). Please let us know if this issue has not been fixed for you.
