### ISSUE TITLE
need custom color format in Camera.outputRenderTexture

### ISSUE THREAD

**Issue by oceancx** [RenderHeads/UnityPlugin-AVProDeckLink#49]
R8G8B8A8 color format is losing quality  , we need R16G16B16A16 above support

**Comment by kahnivore** [comment]
Could you provide more details of your use-case please?

**Comment by oceancx** [comment]
anything new on this issue?

**Comment by oceancx** [comment]
> Could you provide more details of your use-case please?

any news?

**Comment by oceancx** [comment]
@RenderHeadsMrT thanks for your reply, I will try next weekday.

**Comment by oceancx** [comment]
@RenderHeadsMrT, we have tried toggle the hdr option, this works. thanks your help.

**Comment by RenderHeadsMrT** [comment]
Thanks for confirming that fix @oceancx. We'll endeavour to get to your other issue as soon as possible.

Cheers,
