### ISSUE TITLE
Demo 07 can not show both input and ouput

### ISSUE THREAD

**Issue by wsdfz** [RenderHeads/UnityPlugin-AVProDeckLink#5]
I found in avpro decklink 1.7.4. Demo 07 can not show both input and ouput. It can only show one separately.

What should I do to fix it?

**Comment by AndrewRH** [comment]
It should work.  You need a card that can do both input and output, and you also need to set the profile of the card for full-duplex mode.  You can either do this via the Video Setup application which lets you configure the default setup of the card.  Or you can go to the General menu in the Unity component and change the profile there.

Does that help?

**Comment by AndrewRH** [comment]
@wsdfz Thanks for reporting this issue - we have replicated it and it is a bug in the latest version (a regression).  We're working on a fix now and so you should have a fix in the next few days.  I will let you know when there is a new version for you.

Thanks,

**Comment by AndrewRH** [comment]
This should now be fixed - please upgrade to version 1.7.6 and see if that works.

Thanks,
