### ISSUE TITLE
Plugin 1.9.0 not working any more with Windows 7

### ISSUE THREAD

**Issue by pcossinet** [RenderHeads/UnityPlugin-AVProDeckLink#50]
**Describe the bug**
Using Plugin 1.8.6 Decklink output is OK on a Windows 7 config.
After 1.9.0 upgrade, no more SDI output visible, no log or error message but all frames are dropped.
Works really perfectly on Windows 10.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.12f1
 - AVPro DeckLink version: 1.9.0
 - Operating system version: Windows 7
 - Hardware model: HP Z240
 - Desktop Video version: 12.0
 - Video mode (resolution, frame-rate, pixel-format): 1980i50

**To Reproduce**
Just run on Windows 7

**Comment by RenderHeadsMrT** [comment]
Hi @pcossinet,

Are you able to confirm if the just released v1.9.1 fixes this for you?

Cheers,

**Comment by AndrewRH** [comment]
Closing, assumed fixed
