### ISSUE TITLE
With 1.9.0 Decklink in progressive mode, ghost frame can appear

### ISSUE THREAD

**Issue by pcossinet** [RenderHeads/UnityPlugin-AVProDeckLink#53]
**Describe the bug**
Using Plugin 1.8.6 Decklink output is OK on a Windows 10 config.
After 1.9.0 upgrade, sometimes there is a "ghost frame" that can appear sometimes.
Works really perfectly on Windows 10 with Plugin 1.8.6 Decklink

The problem is here only with 1080p50 and 1080p25, no "ghost frame" in 1080i50.
Perhaps it come from double framerate for interleaved mode ?

**Your Setup (please complete the following information):**
 - Unity version: Unity version: 2020.3.12f1
 - AVPro DeckLink version: AVPro DeckLink version: 1.9.0
 - Operating system version: Windows 10
 - Hardware model: i9-10900X, 32Go RAM, RTX 3080
 - Desktop Video version: 12.0
 - Video mode (resolution, frame-rate, pixel-format): 1080p50 & 1080p25

**To Reproduce**
1. Choose 1080p50 or 1080p25 SDI output
2. Play various graphics
4. Sometimes a "ghost" image appear on monitor

**Screenshots**
![image](https://user-images.githubusercontent.com/64129152/138226724-8a4332d1-1a2d-411f-a43c-b93d60f08fd1.png)

**Videos**
https://user-images.githubusercontent.com/64129152/138226528-00782c3e-488a-43a9-b336-6f23e5a1127f.mp4

**Comment by Chris-RH** [comment]
Could not reproduce. Please reopen if this is still an issue.
