### ISSUE TITLE
External Keying - HDRP

### ISSUE THREAD

**Issue by RomainKurtz** [RenderHeads/UnityPlugin-AVProDeckLink#6]
Hello,

I can not get a fill and a key out with the new HDRP. It does not seem to work. The key signal is full white.
The same test with the render legacy works.

AVProDecklink : Version 1.7.4
Blackmagic Decktop Video : Version 11.1
Blackmagic card : Decklink 8K Pro
Unity : Version 2019.2.3f1
Test scene : 08_ExternalKeyingDemo
Deck Link Output -> Video -> Ignore Alpha Channel -> false.

Best,
Rom

**Comment by AndrewRH** [comment]
Thanks for reporting this.  I imagine this is due to shader changes when using HDRP...  We'll investigate.

**Comment by AndrewRH** [comment]
We have replicated this issue.  It seems that Unity have removed alpha channel support for rendertargets in HDRP.  There are a few threads about it here:
https://issuetracker.unity3d.com/issues/hdrp-camera-color-alpha-variable-is-ignored-when-using-hdrp-5-dot-10-dot-0
https://forum.unity.com/threads/alpha-in-render-texture-must-be-alpha.746405/#post-4972694

Sadly it doesn't look like they'll be fixing it - it's just HDRP has such a different design...
It looks like when using HDRP you would have to do some manual rendering to get an alpha channel.  I'm not sure how we can support this in a general case...

**Comment by RomainKurtz** [comment]
Hello  Andrew,
Thank you for watching this. I hope Unity will evolve HDRP in this way.

**Comment by AndrewRH** [comment]
No problem..we'll keep a close eye on this.  It would certainly be very useful to have alpha channel rendering when using LWRP/HDRP...   If you spot any good methods for doing this we would love to know.  I'll leave this issue open for now as others may encounter it too.

**Comment by maximeLong** [comment]
Hey just to clarify - does this mean that this library doesn't work at all in HDRP (specifically 2019.2)? Or is there only a subset of features that won't work?

**Comment by maximeLong** [comment]
* pinging on ^^ question. @AndrewRH

**Comment by AndrewRH** [comment]
It should work in HDRP otherwise, but there is this issue with alpha.

**Comment by AndrewRH** [comment]
So small update on this - In HDRP the default backbuffer pixel format doesn't have an alpha channel - so if you want to do external keying you need to go into the HDRP settings and change the format to one with an alpha channel.

I will close this issue now.

Thanks,
