### ISSUE TITLE
Choppy Animations on Decklink in 1080i50 

### ISSUE THREAD

**Issue by 303er** [RenderHeads/UnityPlugin-AVProDeckLink#60]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
Decklink Output in 1080i50  is choppy and far from smooth. Animations in Game Window are smooth.

**Your Setup (please complete the following information):**
 - Unity version:  2021.3.10f1
 - AVPro DeckLink version: UnityPlugin-AVProDeckLink-v1.9.3-Trial
 - Operating system version: Windows 11
 - Hardware model: UltraStudio HD Mini
 - Cables used: HDMI/SDI
 - Desktop Video version: 12.4
 - Video mode (resolution, frame-rate, pixel-format): 1080i50 ARGB

**To Reproduce**
1.  Open External Keying Demo Scene
2. Insert Cube in Scene.
3. Make loop animation for cube moving horizontally on the screen.
4. Compile Project.
5. Playback will be choppy on Decklink output, even when its smooth in game window.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
[https://drive.google.com/file/d/1tGfCGUz0uuW3RJSpOleyeU-D9q6sPnpz/view?usp=sharing](url)

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RichRH** [comment]
Hi @303er,

Thanks for the clear reproduction steps - I have fixed a recent frame capture bug but will try and replicate your setup to see if I can track any further issues.

Cheers,

**Comment by RichRH** [comment]
Hi @303er,

Just a quick update to say I believe I've located and fixed the issue - should be in the next build hopefully released by early next week.

Cheers,

**Comment by 303er** [comment]
Awesome.
It works great for me now.
We will purchase a license in the next coming days.

Cheers,
Roman

Am Di., 8. Nov. 2022 um 17:13 Uhr schrieb Richard Turnbull <
***@***.***>:
