### ISSUE TITLE
Abdel 1

### ISSUE THREAD

**Issue by Abdel6517** [RenderHeads/UnityPlugin-AVProDeckLink#67]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro DeckLink version: 
 - Operating system version: 
 - Hardware model:
 - Cables used:
 - Desktop Video version:
 - Video mode (resolution, frame-rate, pixel-format): 

**To Reproduce**

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, please can you fill in the form and supply info about your issue.
