### ISSUE TITLE
Decklink IP 2110

### ISSUE THREAD

**Issue by pcossinet** [RenderHeads/UnityPlugin-AVProDeckLink#76]
Hello,

We are using AVPro Decklink today with various cards:
- Decklink Duo 2
- Decklink 4K
- Decklink 8K Pro

Do you plan to support new cards for SMPTE ST2110 ?
- Decklink IP HD
- Decklink IP HD Optical
- Decklink IP/SDI HD

Thanks for your feedback

**Comment by Chris-RH** [comment]
Hi @pcossinet 

From having looked at the SDK in the past, we believe it should work.  However we don't have any of those cards to hand for testing at the moment.

**Comment by v2k** [comment]
Curious if anyone has been able to test these yet?
