### ISSUE TITLE
Decklink Duo 2 card not being detected

### ISSUE THREAD

**Issue by MatthewValverde** [RenderHeads/UnityPlugin-AVProDeckLink#8]
Hello!

Our Team is currently using A Decklink Duo 2 card to test with but we are unable to get it working properly.

Is the plugin compatible with the Decklink Duo 2 and is there anything special that must be completed for it to work properly?

Testing with Unity 2019.6 and Windows 10.
thanks.

**Comment by AndrewRH** [comment]
Hi,

Yes it should work with that card.

Do you have the latest version of our plugin and of the Desktop Video drivers?

Thanks,

**Comment by AndrewRH** [comment]
hmm?

**Comment by AndrewRH** [comment]
I'm closing this ticket as there has been no further details provided.
